### ISSUE TITLE
Add Sonarcloud-Tracking to this Repo

### ISSUE THREAD

**Issue by fkoehne** [viadee/sonarIssueScoring#4]
Because... it would be careless not to :).

**Comment by h-huss** [comment]
Already done: https://sonarcloud.io/dashboard?id=de.viadee%3AsonarIssueScoring

**Comment by fkoehne** [comment]
Nice. Let's add the coverage badge to the readme.

**Comment by h-huss** [comment]
Added. 
There are also a lot of other badges available: "Get project badges" in the bottom-right corner of the above link.

**Comment by fkoehne** [comment]
Thanks. Include more, if you want. The coverage badge is the most important one for me, however. Hence we can close this issue.

The change broke the build, i.e. the security issues found in dependencies since the last build did. Let's follow up on that in issue #2.
