### ISSUE TITLE
Upgrade com.squareup.retrofit2:retrofit dependency to version 2.5.0 or later

### ISSUE THREAD

**Issue by fkoehne** [viadee/sonarIssueScoring#5]
... or try to work without it.

**Comment by h-huss** [comment]
Its only needed for h2o, which also recently upgraded it to 2.4.0.
https://github.com/h2oai/h2o-3/commit/fb4115bbcb08958a30467d008e4c6f99cdc23fc4

**Comment by fkoehne** [comment]
So this should be fixed anlong with #2. Thanks.

**Comment by h-huss** [comment]
It will be 2.4.0, not 2.5.0 as the title requests
